"""Altered LatestReports table

Revision ID: 57f27f360071
Revises: c4241cd49c8c
Create Date: 2026-03-02 23:02:27.974154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '57f27f360071'
down_revision: Union[str, Sequence[str], None] = 'c4241cd49c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stored_reports',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('report_status', postgresql.ENUM('FINAL', 'PRELIMINARY', name='report_status_enum', create_type=False), nullable=False),
    sa.Column('market_type', postgresql.ENUM('LIVE', 'DIRECT', 'VIDEO', name='market_type_enum', create_type=False), nullable=False),
    sa.Column('has_corrections', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['slug'], ['auctions.slug'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_stored_reports_slug'), 'stored_reports', ['slug'], unique=False)
    op.drop_index(op.f('ix_latest_reports_slug'), table_name='latest_reports')
    op.drop_table('latest_reports')
    op.drop_column('reports', 'created_at')
    op.drop_column('reports', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False))
    op.add_column('reports', sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP(0)'), autoincrement=False, nullable=False))
    op.create_table('latest_reports',
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('published_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('report_status', postgresql.ENUM('FINAL', 'PRELIMINARY', name='report_status_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('market_type', postgresql.ENUM('LIVE', 'DIRECT', 'VIDEO', name='market_type_enum', create_type=False), autoincrement=False, nullable=False),
    sa.Column('has_corrections', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['slug'], ['auctions.slug'], name=op.f('fk_latest_reports_slug_auctions')),
    sa.PrimaryKeyConstraint('slug', name=op.f('pk_latest_reports'))
    )
    op.create_index(op.f('ix_latest_reports_slug'), 'latest_reports', ['slug'], unique=False)
    op.drop_index(op.f('ix_stored_reports_slug'), table_name='stored_reports')
    op.drop_table('stored_reports')
    # ### end Alembic commands ###
