"""Removed uuid from Report and added index

Revision ID: 5d7b2e9bafdf
Revises: 57f27f360071
Create Date: 2026-03-11 03:19:28.683098

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5d7b2e9bafdf'
down_revision: Union[str, Sequence[str], None] = '57f27f360071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_uuid'), table_name='reports')
    op.drop_index(op.f('uq_reports_slug_date_no_region'), table_name='reports', postgresql_where='(region IS NULL)')
    op.drop_constraint(op.f('uq_reports_slug_date_region'), 'reports', type_='unique')
    op.drop_column('reports', 'uuid')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_reports_slug_date_region'), 'reports', ['auction_slug', 'report_date', 'region'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_reports_slug_date_no_region'), 'reports', ['auction_slug', 'report_date'], unique=True, postgresql_where='(region IS NULL)')
    op.create_index(op.f('ix_reports_uuid'), 'reports', ['uuid'], unique=True)
    op.alter_column('reports', 'region',
               existing_type=postgresql.ENUM('EMPTY', 'NORTH_CENTRAL', 'SOUTH_CENTRAL', name='region_enum'),
               type_=postgresql.ENUM('NORTH_CENTRAL', 'SOUTH_CENTRAL', name='regionoptions'),
               nullable=True)
    # ### end Alembic commands ###
