"""add unique constraint to reports

Revision ID: 64896e3a3f95
Revises: 5d7b2e9bafdf
Create Date: 2026-03-11 04:35:34.373109

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '64896e3a3f95'
down_revision: Union[str, Sequence[str], None] = '5d7b2e9bafdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reports', 'region',
               existing_type=postgresql.ENUM('NORTH_CENTRAL', 'SOUTH_CENTRAL', 'EMPTY', name='region_enum'),
               nullable=False)
    op.create_unique_constraint('uq_report_slug_date_region', 'reports', ['auction_slug', 'report_date', 'region'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_report_slug_date_region', 'reports', type_='unique')
    op.alter_column('reports', 'region',
               existing_type=postgresql.ENUM('NORTH_CENTRAL', 'SOUTH_CENTRAL', 'EMPTY', name='region_enum'),
               nullable=True)
    # ### end Alembic commands ###
