"""added tables

Revision ID: 90ceb9711395
Revises: 
Create Date: 2026-02-20 10:47:44.082984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '90ceb9711395'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auctions',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market_type', postgresql.ENUM('LIVE', 'DIRECT', 'VIDEO', name='market_type_enum'), nullable=False),
    sa.Column('offset', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_auctions_display_name'), 'auctions', ['display_name'], unique=True)
    op.create_index(op.f('ix_auctions_report_title'), 'auctions', ['report_title'], unique=True)
    op.create_index(op.f('ix_auctions_slug'), 'auctions', ['slug'], unique=False)
    op.create_table('latest_reports',
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('report_status', postgresql.ENUM('FINAL', 'PRELIMINARY', name='report_status_enum'), nullable=False),
    sa.Column('market_type', postgresql.ENUM('LIVE', 'DIRECT', 'VIDEO', name='market_type_enum'), nullable=True),
    sa.Column('has_corrections', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['slug'], ['auctions.slug'], ),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_index(op.f('ix_latest_reports_slug'), 'latest_reports', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_latest_reports_slug'), table_name='latest_reports')
    op.drop_table('latest_reports')
    op.drop_index(op.f('ix_auctions_slug'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_report_title'), table_name='auctions')
    op.drop_index(op.f('ix_auctions_display_name'), table_name='auctions')
    op.drop_table('auctions')
    # ### end Alembic commands ###
