"""Added Reports Table

Revision ID: c4241cd49c8c
Revises: 90ceb9711395
Create Date: 2026-02-26 22:57:35.463942

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c4241cd49c8c'
down_revision: Union[str, Sequence[str], None] = '90ceb9711395'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('current_timestamp(0)'), nullable=False),
    sa.Column('uuid', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_end_date', sa.Date(), nullable=False),
    sa.Column('published_date', sa.DateTime(), nullable=False),
    sa.Column('report_status', postgresql.ENUM('FINAL', 'PRELIMINARY', name='report_status_enum', create_type=False), nullable=False),
    sa.Column('region', sa.Enum('NORTH_CENTRAL', 'SOUTH_CENTRAL', name='regionoptions'), nullable=True),
    sa.Column('head1', sa.Integer(), nullable=False),
    sa.Column('weight1', sa.Float(), nullable=False),
    sa.Column('price1', sa.Float(), nullable=False),
    sa.Column('head2', sa.Integer(), nullable=False),
    sa.Column('weight2', sa.Float(), nullable=False),
    sa.Column('price2', sa.Float(), nullable=False),
    sa.Column('head3', sa.Integer(), nullable=False),
    sa.Column('weight3', sa.Float(), nullable=False),
    sa.Column('price3', sa.Float(), nullable=False),
    sa.Column('head4', sa.Integer(), nullable=False),
    sa.Column('weight4', sa.Float(), nullable=False),
    sa.Column('price4', sa.Float(), nullable=False),
    sa.Column('head5', sa.Integer(), nullable=False),
    sa.Column('weight5', sa.Float(), nullable=False),
    sa.Column('price5', sa.Float(), nullable=False),
    sa.Column('auction_slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['auction_slug'], ['auctions.slug'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('auction_slug', 'report_date', 'region', name='uq_reports_slug_date_region')
    )
    op.create_index(op.f('ix_reports_uuid'), 'reports', ['uuid'], unique=True)
    op.create_index('uq_reports_slug_date_no_region', 'reports', ['auction_slug', 'report_date'], unique=True, postgresql_where=sa.text('region IS NULL'))
    op.alter_column('latest_reports', 'market_type',
               existing_type=postgresql.ENUM('LIVE', 'DIRECT', 'VIDEO', name='market_type_enum', create_type=False),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('latest_reports', 'market_type',
               existing_type=postgresql.ENUM('LIVE', 'DIRECT', 'VIDEO', name='market_type_enum'),
               nullable=True)
    op.drop_index('uq_reports_slug_date_no_region', table_name='reports', postgresql_where=sa.text('region IS NULL'))
    op.drop_index(op.f('ix_reports_uuid'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
